# .github/workflows/update_site.yml
name: Atualizar Links do Telegram

# Define o gatilho: Executa a cada hora ou manualmente
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      
      # Passo 1: Checkout do Código
      - name: Checkout do Repositório
        uses: actions/checkout@v4
        
      # Passo 2: Configuração do Python
      - name: Configurar Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      # Passo 3: Instalação de Dependências
      - name: Instalar Telethon
        # Você deve ter um 'requirements.txt' que lista a biblioteca 'telethon'
        run: pip install -r requirements.txt
        
      # Passo 4: Execução do Script (AGORA COM TODOS OS SECRETS)
      - name: Executar bot_videos.py
        run: python bot_videos.py
        # ESTA SECÇÃO INJETA OS SECRETS
        env:
          # Variáveis de autenticação
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          # Variável para o nome do grupo/canal
          GRUPO_USERNAME: ${{ secrets.GRUPO_USERNAME }}
          
      # Passo 5: Envio do Novo HTML (O Site Atualizado)
      - name: Commit e Push do HTML Atualizado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'action@github.com'
          message: 'Atualização automática do site via GitHub Actions'
          add: 'index.html' # CORRIGIDO: Agora faz commit do index.html
